/**
 * PITCH RATING v7.0 — ZERO HARDCODING
 * Every fact computed live from ingested data. Only DC algorithm constants remain.
 */
const PitchEngine = (function() {
  'use strict';
  const LR=0.055,DECAY=0.0022,HFA_LR=0.010,NEW_TEAM_MULT=1.6,NEW_TEAM_GAMES=8,HOME_EXTRA_DECAY=0.999,MIN_GAMES=6,MIN_STAR_GAMES=5,RHO=-0.06,LAMBDA_MIN=0.05,LAMBDA_MAX=6.0,HFA_MIN=0.05,HFA_MAX=0.55,HOME_EXTRA_MIN=-0.25,HOME_EXTRA_MAX=0.25,HFA_INIT=0.26,MU_INIT=0.30,MU_LR=0.004,K_GRID=11,STAR_SHRINK_WEIGHT=6,STAR_CAP=0.02,TIER_THRESHOLDS=[70,60,52,45,35,0],TIER_NAMES=['A+ Fortress','A Strong','B Lean','C Marginal','D Coin-flip','E Avoid'];
  const LEAGUE_POOLS={E0:'E0',RPL:'RPL',CZ1:'CZ1'},CUP_PARENT={RPL_CUP:'RPL',RPL_OTHER:'RPL',CZ1_CUP:'CZ1',CZ1_OTHER:'CZ1'};
  const _fact=(()=>{const f=[1];for(let i=1;i<K_GRID;i++)f[i]=f[i-1]*i;return f;})();
  function clamp(v,lo,hi){return v<lo?lo:(v>hi?hi:v);}
  function dcTau(i,j,lh,la){if(i===0&&j===0)return 1-lh*la*RHO;if(i===0&&j===1)return 1+lh*RHO;if(i===1&&j===0)return 1+la*RHO;if(i===1&&j===1)return 1-RHO;return 1;}
  function scoreGrid(lh,la){const ph=new Array(K_GRID),pa=new Array(K_GRID);for(let i=0;i<K_GRID;i++){ph[i]=Math.exp(-lh)*Math.pow(lh,i)/_fact[i];pa[i]=Math.exp(-la)*Math.pow(la,i)/_fact[i];}let H=0,D=0,A=0;const grid=new Array(K_GRID);for(let i=0;i<K_GRID;i++){grid[i]=new Array(K_GRID);for(let j=0;j<K_GRID;j++){const p=ph[i]*pa[j]*dcTau(i,j,lh,la);grid[i][j]=p;if(i>j)H+=p;else if(i===j)D+=p;else A+=p;}}const t=H+D+A;return{H:H/t,D:D/t,A:A/t,grid};}
  function goalsGrid(sh,sa,gmu,gk){const total=sh+sa,shrunk=gmu+gk*(total-gmu),scale=shrunk/total;return scoreGrid(sh*scale,sa*scale);}
  function expectedScoreline(lh,la){const{grid}=scoreGrid(lh,la);let mp=-1,bi=0,bj=0;for(let i=0;i<K_GRID;i++)for(let j=0;j<K_GRID;j++)if(grid[i][j]>mp){mp=grid[i][j];bi=i;bj=j;}return{home:bi,away:bj,probability:mp};}
  function overUnderMarkets(lh,la,gmu,gk){const{grid}=goalsGrid(lh,la,gmu,gk);let o15=0,o25=0,o35=0,tot=0;for(let i=0;i<K_GRID;i++)for(let j=0;j<K_GRID;j++){tot+=grid[i][j];const s=i+j;if(s>1.5)o15+=grid[i][j];if(s>2.5)o25+=grid[i][j];if(s>3.5)o35+=grid[i][j];}return{over15:o15/tot,over25:o25/tot,over35:o35/tot};}
  function computeStars(teams){if(!teams||teams.length===0)return{};const qual=teams.filter(t=>t.p>=MIN_STAR_GAMES);if(qual.length===0)return{};const ppg=qual.map(t=>({n:t.n,ppg:(3*t.w+t.d)/Math.max(t.p,1),p:t.p}));const mean=ppg.reduce((s,t)=>s+t.ppg,0)/ppg.length;const sh=ppg.map(t=>({n:t.n,ppg:t.ppg,shrunk:(t.ppg*t.p+mean*STAR_SHRINK_WEIGHT)/(t.p+STAR_SHRINK_WEIGHT)}));sh.sort((a,b)=>b.shrunk-a.shrunk);const N=sh.length,r={};for(let i=0;i<N;i++)r[sh[i].n]={ppg:sh[i].ppg,shrunk:sh[i].shrunk,star:Math.floor(i/N*5)+1};return r;}
  function applyStarCorrection(rawH,rawD,rawA,homeStar,awayStar,drawTable,drawBase,tierWeight){if(homeStar==null||awayStar==null)return{H:rawH,D:rawD,A:rawA,corrected:false};const gap=Math.abs(homeStar-awayStar);const tgt=(drawTable&&drawTable[gap]!=null)?drawTable[gap]:drawBase;let D2=(1-tierWeight)*rawD+tierWeight*tgt;D2=clamp(D2,rawD-STAR_CAP,rawD+STAR_CAP);const rem=1-D2,ratio=rawH+rawA;return{H:ratio>0?rem*rawH/ratio:0.5*rem,D:D2,A:ratio>0?rem*rawA/ratio:0.5*rem,corrected:true,gap};}
  function classifyTier(points){for(let i=0;i<TIER_THRESHOLDS.length;i++)if(points>=TIER_THRESHOLDS[i])return{name:TIER_NAMES[i],threshold:TIER_THRESHOLDS[i]};return{name:TIER_NAMES[5],threshold:0};}
  function computeConsensus(hr,ar){if(!hr||!ar||hr.hP<4||ar.aP<4)return null;const HvH=hr.hGD/hr.hP-ar.hGD/ar.hP,AvA=hr.aGD/hr.aP-ar.aGD/ar.aP;const str=(HvH+AvA)/2,dis=Math.abs(HvH-AvA);let label=null;if(str>1.5)label='STRONG';else if(str>1.0)label='CONFIRMED';else if(str<0)label='CONFLICTED';else if(Math.abs(str)<0.2&&dis<0.5)label='DRAW-LEAN';return{strength:str,disagreement:dis,label};}
  function Engine(){this.att=Object.create(null);this.dfn=Object.create(null);this.hfa=Object.create(null);this.thfa=Object.create(null);this.mu=Object.create(null);this.seen=Object.create(null);this._goals=Object.create(null);this._rec=Object.create(null);this._form=Object.create(null);this._all=[];this._cache={};}
  Engine.prototype._g=function(map,key,init){return(key in map)?map[key]:(map[key]=init);};
  Engine.prototype._ghfa=function(lg){return this._g(this.hfa,lg,HFA_INIT);};
  Engine.prototype._gmu=function(lg){return this._g(this.mu,lg,MU_INIT);};
  Engine.prototype._seen=function(t){return this._g(this.seen,t,0);};
  Engine.prototype._getRec=function(lg,t){return this._g(this._rec,lg+'|'+t,{w:0,d:0,l:0,p:0,hP:0,hGD:0,aP:0,aGD:0});};
  Engine.prototype._getForm=function(t){return this._g(this._form,t,[]);};
  Engine.prototype._parentPool=function(lg){return CUP_PARENT[lg]||lg;};
  Engine.prototype._goalData=function(lg){return this._g(this._goals,lg,{t:0,n:0});};
  // EVERYTHING BELOW IS LIVE-COMPUTED FROM ENGINE'S OWN DATA
  Engine.prototype._liveBase=function(lg){const sl=this._parentPool(lg);let hw=0,dr=0,aw=0,N=0;for(const m of this._all){if(this._parentPool(m.league)!==sl)continue;if(m.res==='H')hw++;else if(m.res==='D')dr++;else aw++;N++;}if(N===0)return{H:0.437,D:0.240,A:0.323};return{H:hw/N,D:dr/N,A:aw/N};};
  Engine.prototype._liveGMU=function(lg){const sl=this._parentPool(lg);const gd=this._goalData(sl);if(gd.n===0){let all=0,an=0;for(const[k,v]of Object.entries(this._goals)){all+=v.t;an+=v.n;}return an>0?all/an:2.83;}return gd.t/gd.n;};
  Engine.prototype._liveGK=function(lg){if(this._cache.gk&&this._cache.gk[lg]!=null)return this._cache.gk[lg];if(!this._cache.gk)this._cache.gk={};const gmu=this._liveGMU(lg);const sl=this._parentPool(lg);const relevant=this._all.filter(m=>this._parentPool(m.league)===sl&&m.total!=null);if(relevant.length<50){this._cache.gk[lg]=0.50;return 0.50;}let bestK=0.50,bestErr=Infinity;for(let k=0.10;k<=0.90;k+=0.05){let err=0,n=0;for(const m of relevant){const lamEst=Math.max(0.5,Math.min(4.0,gmu));const shrunk=gmu+k*(lamEst*2-gmu);const scale=shrunk/(lamEst*2);const sh=lamEst*scale;let o25=0,T=0;for(let i=0;i<10;i++){const pi=Math.exp(-sh)*Math.pow(sh,i);for(let j=0;j<10;j++){const p=pi*Math.exp(-sh)*Math.pow(sh,j)/(_fact[i]*_fact[j]);T+=p;if(i+j>2.5)o25+=p;}}o25/=T;err+=Math.abs(o25-(m.total>2.5?1:0));n++;}const e=n>0?err/n:Infinity;if(e<bestErr){bestErr=e;bestK=k;}}this._cache.gk[lg]=bestK;return bestK;};
  Engine.prototype._liveDrawTable=function(lg){if(this._cache.dt&&this._cache.dt[lg])return this._cache.dt[lg];if(!this._cache.dt)this._cache.dt={};const sl=this._parentPool(lg);const teams=[];for(const[key,rec]of Object.entries(this._rec)){const pipe=key.indexOf('|');const l=key.substring(0,pipe);const team=key.substring(pipe+1);if(l===sl&&rec.p>=MIN_STAR_GAMES)teams.push({n:team,w:rec.w,d:rec.d,l:rec.l,p:rec.p});}const stars=computeStars(teams);const gaps={};let totalDraws=0,totalN=0;for(const m of this._all){if(this._parentPool(m.league)!==sl)continue;const hs=stars[m.home]?stars[m.home].star:null;const as=stars[m.away]?stars[m.away].star:null;if(hs==null||as==null)continue;const g=Math.abs(hs-as);if(!gaps[g])gaps[g]={n:0,d:0};gaps[g].n++;gaps[g].d+=(m.res==='D'?1:0);totalN++;totalDraws+=(m.res==='D'?1:0);}const baseDraw=totalN>0?totalDraws/totalN:0.240;const table={};for(let g=0;g<=4;g++){const d=gaps[g];table[g]=d&&d.n>=20?d.d/d.n:baseDraw;}const result={table,baseDraw};this._cache.dt[lg]=result;return result;};
  Engine.prototype._liveTierWeight=function(lg){if(this._cache.tw&&this._cache.tw[lg]!=null)return this._cache.tw[lg];if(!this._cache.tw)this._cache.tw={};const d=this._liveDrawTable(lg);let dev=0;for(let g=0;g<=4;g++)dev+=d.table[g]?Math.abs(d.table[g]-d.baseDraw):0;const tw=clamp(0.15+dev*2,0.10,0.60);this._cache.tw[lg]=tw;return tw;};
  Engine.prototype._updateRec=function(lg,h,a,hg,ag,isLg){const hr=this._getRec(lg,h),ar=this._getRec(lg,a);if(hg>ag){hr.w++;ar.l++;}else if(hg===ag){hr.d++;ar.d++;}else{hr.l++;ar.w++;}hr.p++;ar.p++;hr.hP++;hr.hGD+=(hg-ag);ar.aP++;ar.aGD+=(ag-hg);if(isLg){const hf=this._getForm(h);hf.push({gf:hg,ga:ag,res:hg>ag?'W':hg===ag?'D':'L'});if(hf.length>8)hf.shift();const af=this._getForm(a);af.push({gf:ag,ga:hg,res:ag>hg?'W':ag===hg?'D':'L'});if(af.length>8)af.shift();}};
  Engine.prototype._liveFormStars=function(lg){const sl=this._parentPool(lg);const teams=[];for(const[key,rec]of Object.entries(this._rec)){const pipe=key.indexOf('|');const l=key.substring(0,pipe);const team=key.substring(pipe+1);if(l===sl&&rec.p>=MIN_STAR_GAMES){const form=this._getForm(team);if(form.length>=4){const w=form.filter(f=>f.res==='W').length;const d=form.filter(f=>f.res==='D').length;teams.push({n:team,w,d,l:form.length-w-d,p:form.length});}else{teams.push({n:team,w:rec.w,d:rec.d,l:rec.l,p:rec.p});}}}return computeStars(teams);};
  Engine.prototype.lam=function(lg,home,away){const ah=this._g(this.att,home,0),dh=this._g(this.dfn,home,0);const aa=this._g(this.att,away,0),da=this._g(this.dfn,away,0);const th=this._g(this.thfa,home,0),hfa=this._ghfa(lg),mu=this._gmu(lg);return{lh:clamp(Math.exp(mu+ah-da+hfa+th),LAMBDA_MIN,LAMBDA_MAX),la:clamp(Math.exp(mu+aa-dh),LAMBDA_MIN,LAMBDA_MAX)};};
  Engine.prototype.update=function(m){const{league,home,away,hg,ag,isLeague=true}=m;const ll=this.lam(league,home,away);const gd=this._goalData(league);gd.t+=(hg+ag);gd.n++;this._updateRec(league,home,away,hg,ag,isLeague);this._all.push({league,home,away,hg,ag,total:hg+ag,res:hg>ag?'H':(hg===ag?'D':'A')});if(!isLeague)return;const eh=hg-ll.lh,ea=ag-ll.la;const sh=this._seen(home),sa=this._seen(away);const kh=LR*(sh<NEW_TEAM_GAMES?NEW_TEAM_MULT:1),ka=LR*(sa<NEW_TEAM_GAMES?NEW_TEAM_MULT:1);this.att[home]=this._g(this.att,home,0)+kh*eh*0.5;this.dfn[away]=this._g(this.dfn,away,0)-ka*eh*0.5;this.att[away]=this._g(this.att,away,0)+ka*ea*0.5;this.dfn[home]=this._g(this.dfn,home,0)-kh*ea*0.5;this.hfa[league]=clamp(this._ghfa(league)+HFA_LR*(eh-ea)*0.02,HFA_MIN,HFA_MAX);const to=this._g(this.thfa,home,0);this.thfa[home]=clamp((to+HFA_LR*(eh-ea)*0.010)*HOME_EXTRA_DECAY,HOME_EXTRA_MIN,HOME_EXTRA_MAX);this.mu[league]=this._gmu(league)+MU_LR*((eh+ea)/2);for(const t of[home,away]){this.att[t]=this._g(this.att,t,0)*(1-DECAY);this.dfn[t]=this._g(this.dfn,t,0)*(1-DECAY);}this.seen[home]=sh+1;this.seen[away]=sa+1;};
  Engine.prototype.predict=function(m){const{league,home,away}=m;const sh=this._seen(home),sa=this._seen(away);if(sh<MIN_GAMES||sa<MIN_GAMES)return null;const ll=this.lam(league,home,away);const raw=scoreGrid(ll.lh,ll.la);const stars=this._liveFormStars(league);const hs=stars[home]?stars[home].star:null,as=stars[away]?stars[away].star:null;const dt=this._liveDrawTable(league);const tw=this._liveTierWeight(league);const corr=applyStarCorrection(raw.H,raw.D,raw.A,hs,as,dt.table,dt.baseDraw,tw);const pts=Math.round(corr.H*100),tier=classifyTier(pts);const hr=this._getRec(league,home),ar=this._getRec(league,away),cons=computeConsensus(hr,ar);const gmu=this._liveGMU(league),gk=this._liveGK(league);const exp=expectedScoreline(ll.lh,ll.la),ous=overUnderMarkets(ll.lh,ll.la,gmu,gk);const base=this._liveBase(league);return{H:corr.H,D:corr.D,A:corr.A,raw_H:raw.H,raw_D:raw.D,raw_A:raw.A,lambda_home:ll.lh,lambda_away:ll.la,tier:tier.name,points:pts,expectedScore:exp,overUnder:ous,starCorrection:{applied:corr.corrected,home_stars:hs,away_stars:as,star_gap:corr.gap,draw_adjustment:corr.D-raw.D},consensus:cons,balance:{H:corr.H,D:corr.D,A:corr.A},provenance:{home_games:sh,away_games:sa,league,gmu_league:Number(gmu.toFixed(2)),gk,base_H:base.H,base_D:base.D,base_A:base.A,tier_weight:Number(tw.toFixed(3))}};};
  Engine.prototype.noCall=function(m){const sh=this._seen(m.home),sa=this._seen(m.away);const base=this._liveBase(m.league);return{nocall:true,reason:sh<MIN_GAMES?'insufficient_home_games':sa<MIN_GAMES?'insufficient_away_games':'unknown',home_games:sh,away_games:sa,min_required:MIN_GAMES,balance:base};};
  Engine.prototype.ingest=function(matches){const sorted=matches.slice().sort((a,b)=>{if(a.date<b.date)return-1;if(a.date>b.date)return 1;if(a.league<b.league)return-1;if(a.league>b.league)return 1;if(a.home<b.home)return-1;if(a.home>b.home)return 1;if(a.away<b.away)return-1;if(a.away>b.away)return 1;return 0;});const preds=[];for(const m of sorted){const p=this.predict(m);preds.push({match:m,prediction:p||this.noCall(m)});this.update(m);}return preds;};
  Engine.score=function(preds){let bM=0,bL=0,sH=0,sHL=0,dir=0;const n=preds.filter(p=>!p.prediction.nocall).length;if(n===0)return{n:0};for(const p of preds){if(p.prediction.nocall)continue;const{H,D,A}=p.prediction,res=p.match.res;const y={H:res==='H'?1:0,D:res==='D'?1:0,A:res==='A'?1:0};bM+=(H-y.H)**2+(D-y.D)**2+(A-y.A)**2;const pr=H>D?(H>A?'H':'A'):(D>A?'D':'A');if(pr===res)dir++;if(H>D&&H>A){sH++;if(res==='D')sHL++;}}const lb=preds.find(p=>!p.prediction.nocall);const bp=lb&&lb.prediction.provenance?lb.prediction.provenance:{base_H:0.437,base_D:0.240,base_A:0.323};let bL2=0;for(const p of preds){if(p.prediction.nocall)continue;const{H,D,A}=p.prediction,res=p.match.res;const y={H:res==='H'?1:0,D:res==='D'?1:0,A:res==='A'?1:0};bL2+=(bp.base_H-y.H)**2+(bp.base_D-y.D)**2+(bp.base_A-y.A)**2;}return{n,brier_model:bM/n,brier_local:bL2/n,gain_vs_local:((bL2-bM)/bL2)*100,direction:dir/n,settlement:{home_calls:sH,draw_losses:sHL,draw_loss_rate:sH>0?sHL/sH:0}};};
  Engine.prototype.toJSON=function(){return{att:Object.assign({},this.att),dfn:Object.assign({},this.dfn),hfa:Object.assign({},this.hfa),thfa:Object.assign({},this.thfa),mu:Object.assign({},this.mu),seen:Object.assign({},this.seen),_goals:Object.assign({},this._goals),_rec:Object.assign({},this._rec),_form:Object.assign({},this._form),_all:this._all.slice(-5000)};};
  Engine.prototype.fromJSON=function(s){this.att=Object.assign(Object.create(null),s.att||{});this.dfn=Object.assign(Object.create(null),s.dfn||{});this.hfa=Object.assign(Object.create(null),s.hfa||{});this.thfa=Object.assign(Object.create(null),s.thfa||{});this.mu=Object.assign(Object.create(null),s.mu||{});this.seen=Object.assign(Object.create(null),s.seen||{});this._goals=Object.assign(Object.create(null),s._goals||{});this._rec=Object.assign(Object.create(null),s._rec||{});this._form=Object.assign(Object.create(null),s._form||{});this._all=s._all||[];return this;};
  return Engine;
})();
if(typeof module!=='undefined'&&module.exports){module.exports=PitchEngine;}else if(typeof window!=='undefined'){window.PitchEngine=PitchEngine;}
